DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
	id BIGINT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE url_checks (
	id BIGINT PRIMARY KEY,
	url_id BIGINT REFERENCES urls (id),
	status_code int,
	h1 VARCHAR(70),
	title VARCHAR(110),
	description VARCHAR(160),
	created_at DATE DEFAULT CURRENT_TIMESTAMP
);
